config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    # :registrations => 'signups',
    :sessions => 'users/sessions'   
  } 
  devise_scope :user do
    # get "user/:id", :to => "users/registrations#detail"
    get "user/:id", :to => "items#index"
    # get "signup", :to => "users/registrations#new"
    get "signup", :to => "users/registrations#new"
    post "signup", :to => "users/registrations#create"
    # get "signup", :to => "signups#new"
    # post "signup", :to => "signups#create"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "sign_in" => "devise/sessions#new"
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # get "signup", :to => "signups#new"
  # post "signup", :to => "signups#create"

  resources :items do
    collection do
      get :show_myself
      get :show_close_myself
      get :show_sell
      get :show_watch_list
    end
  end

  post   '/like/:item_id' => 'likes#like',   as: 'like'
  delete '/like/:item_id' => 'likes#unlike', as: 'unlike'

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(item_id: @item.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(item_id: @item.id)
    like.destroy
  end

  private

  def set_variables
    @item = Item.find(params[:item_id])
    @id_name = "#like-link-#{@item.id}"
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.haml
.like-link{:id => "like-link-#{item.id}"}
  - if current_user == nil
    .iine__button
      %i.far.fa-bookmark
      #{item.likes.count}
  - elsif current_user.id == item.user.id
    .iine__button
      %i.fas.fa-bookmark.orange
      #{item.likes.count}
  - elsif current_user.likes.find_by(item_id: item.id) 
    = link_to unlike_path(item.id), method: :delete, remote: true do
      .iine__button
        %i.fas.fa-bookmark.yellow
        #{item.likes.count}
  - else
    = link_to like_path(item.id), method: :post, remote: true do
      .iine__button
        %i.far.fa-bookmark
        #{item.likes.count}

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", item: @item  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", item: @item  )) %>');