config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    # :registrations => 'signups',
    :sessions => 'users/sessions'   
  } 
  devise_scope :user do
    # get "user/:id", :to => "users/registrations#detail"
    get "user/:id", :to => "items#index"
    # get "signup", :to => "users/registrations#new"
    get "signup", :to => "users/registrations#new"
    post "signup", :to => "users/registrations#create"
    # get "signup", :to => "signups#new"
    # post "signup", :to => "signups#create"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "sign_in" => "devise/sessions#new"
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # get "signup", :to => "signups#new"
  # post "signup", :to => "signups#create"

  resources :items do
    collection do
      get :show_myself
      get :show_close_myself
      get :show_sell
      get :show_watch_list
    end
  end

  post   '/like/:item_id' => 'likes#like',   as: 'like'
  delete '/like/:item_id' => 'likes#unlike', as: 'unlike'

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  validates :title, length: { in: 1..50 }
  validates :price, length: { in: 1..11 }
  validates :details, presence: true, length: { in: 1..150 }

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy, :show_myself, :show_close_myself, :show_sell, :show_watch_list]
  # GET /items
  # GET /items.json
  def index
    @items ||= Item.all.order(created_at: "DESC").page(params[:page])
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @sell_user = User.find_by(id: @item.seller_id)
  end

  def show_myself
    @items = Item.where(user_id: current_user.id).where(seller_id: nil).order(created_at: "DESC").page(params[:page])
  end

  def show_close_myself
    @items = Item.where(user_id: current_user.id).where.not(seller_id: nil).order(created_at: "DESC").page(params[:page])
  end

  def show_sell
    @items = Item.where(seller_id: current_user.id).order(created_at: "DESC").page(params[:page])
  end

  def show_watch_list
    ids = Like.where(user_id: current_user.id).pluck(:item_id)
    @items = Item.where(id: ids).order(created_at: "DESC").page(params[:page])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :details, :price, :seller_id)
      # .merge(user_id: current_user.id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      %ul
        - @item.errors.full_messages.each do |message|
          %li= message

  .field-box
    .field-box__title
      = f.label :title, "タイトル"
    .field-box__form
      「
      = f.text_field :title, class: "form-size-title"
      」を買います！！
  .field-box
    .field-box__title
      = f.label :price, "値段"
    .field-box__form
      = f.number_field :price, class: "form-size-price"
      ギル
  .field-box
    .field-box__title
      %i.fas.fa-book-reader
      = f.label :details, "詳細"
    .field-box__form
      = f.text_area :details, class: "form-size-details"
  .submit-box
    -if @item.id == nil
      = f.submit '募集する', class: "btn-flat-border btn-width100"
    -else
      = f.submit '編集する', class: "btn-flat-border btn-width100"

app/views/items/_item.html.haml
= render 'likes/like', item: item

app/views/items/_side-menu.html.haml
#wrapper
  .side-menu.shadow 
    .side-menu__page-title
      MENU
    - if user_signed_in?
      .side-menu__list.link-hover
        = link_to "「買います」募集一覧", items_path
      .side-menu__list.link-hover
        = link_to new_item_path do
          %i.fas.fa-bookmark.orange
          「買います」募集を作る
      .side-menu__list.link-hover
        = link_to show_myself_items_path do
          %i.fas.fa-bookmark.orange
          「買います」募集をした商品 - 募集中
      .side-menu__list.link-hover
        = link_to show_close_myself_items_path do
          %i.fas.fa-bookmark.orange
          「買います」募集をした商品 - 売買成立
      .side-menu__list.link-hover
        = link_to '「売ります」をした商品 - 一覧', show_sell_items_path
      .side-menu__list.link-hover
        = link_to show_watch_list_items_path do
          %i.fas.fa-bookmark.yellow
          ウォッチリスト
      .side-menu__empty-box
    - else
      .side-menu__list.link-hover
        = link_to "ログイン", login_path
      .side-menu__list.link-hover
        = link_to "新規登録", signup_path
      .side-menu__list.link-hover
        = link_to "「買います」募集一覧", items_path
      .side-menu__empty-box

app/views/items/edit.html.haml
#wrapper
  .main
    .main__list
      .main__list__page-title
        「買います」募集を編集する
      .item-box
        = render 'form'
        .back-edit-destroy-box.margin-top-10
          .back-edit-destroy-box__back
            = link_to '戻る', items_path

    .main__side-menu
      = render 'side-menu'

app/views/items/index.html.haml
#wrapper
  .main
    .main__list.shadow
      .main__list__page-title
        「買います」募集一覧
      - @items.each do |item|
        = link_to(item) do
          .item-container.link-hover
            - if item.seller_id != nil
              .triangle
              .item-container__day
                = item.created_at.to_s(:datetime_jp)
              .item-container__title
                = "「#{item.title}」"
              .item-container__price
                = "値段：#{item.price.to_s(:delimited)} ギル"
            - else
              .item-container__day
                = item.created_at.to_s(:datetime_jp)
              .item-container__title
                = "「#{item.title}」を買います！！"
              .item-container__price
                = "値段：#{item.price.to_s(:delimited)} ギル"
            .item-container__name
              .user-box
                .user-box__face
                  %i.fas.fa-user
                .user-box__name
                  = item.user.name
                  %br
                  .form-size-server-dc
                    = "#{item.user.dc}(#{item.user.server})"
            - if current_user == nil
            - elsif current_user.id == item.user_id and item.seller_id == nil
              .item-container__edit-destroy-box
                = link_to '編集', edit_item_path(item)
                = link_to '削除', item, class: "margin-left-10", method: :delete, data: { confirm: '本当に削除しますか?' }
            .item-container__watch
              = render partial: 'items/item', locals:{ item: item }

      .main__list__pagination-box
        = paginate @items


    .main__side-menu
      = render 'side-menu'

app/views/items/new.html.haml
#wrapper
  .main
    .main__list.shadow
      .main__list__page-title
        「買います」募集を作る
      .item-box
        = render 'form'
        .back-edit-destroy-box.margin-top-10
          .back-edit-destroy-box__back
            = link_to '戻る', items_path

    .main__side-menu
      = render 'side-menu'

app/views/items/show.html.haml
#wrapper
  .main
    .main__list.shadow
      .main__list__page-title
        「買います」募集の詳細
      .item-box
        .item-box__name.margin-bottom-10.margin-fix
          = link_to @item.user.url, target: "_blank" do
            .user-box
              .user-box__face
                %i.fas.fa-user
              .user-box__name
                = @item.user.name
                %br
                .form-size-server-dc
                  = "#{@item.user.dc}(#{@item.user.server})"
        - if @item.seller_id != nil
          .triangle
          .item-box__day
            = @item.created_at.to_s(:datetime_jp)
            = render partial: 'items/item', locals:{ item: @item }
          .item-box__title
            = "「#{@item.title}」"
          .item-box__price
            = "値段：#{@item.price.to_s(:delimited)} ギル"
          .item-box__details
            .details-border
              %i.fas.fa-book-reader
              詳細
            = @item.details
          - if current_user == nil
          - elsif @item.seller_id == current_user.id
            .transaction-details.margin-top-10
              = "あなたは#{@item.user.name}さんへ商品を売りました。"
              %br
              %br
              = "商品：#{@item.title}"
              %br
              = "お金：#{@item.price}"
            .transaction-box
              .transaction-box__name
                あなた
              .transaction-box__arrow
                .arrow-box
                  .arrow-box__upper
                    .arrow_r
                      商品
                  .arrow-box__lower
                    .arrow_l
                      お金
              .transaction-box__name
                = link_to @item.user.url, target: "_blank" do
                  = @item.user.name
                  %br
                  .form-size-server-dc
                    = "#{@item.user.dc}(#{@item.user.server})"
          - elsif @item.seller_id != current_user.id and @item.user.id != current_user.id
          - else
            .transaction-details.margin-top-10
              = "あなたは#{@sell_user.name}さんから商品を買いました。"
              %br
              %br
              = "お金：#{@item.price}"
              %br
              = "商品：#{@item.title}"
            .transaction-box
              .transaction-box__name
                あなた
              .transaction-box__arrow
                .arrow-box
                  .arrow-box__upper
                    .arrow_r
                      お金
                  .arrow-box__lower
                    .arrow_l
                      商品
              .transaction-box__name
                = @sell_user.name
        - else
          .item-box__day
            = @item.created_at.to_s(:datetime_jp)
            = render partial: 'items/item', locals:{ item: @item }
          .item-box__title
            = "「#{@item.title}」を買います！！"
          .item-box__price
            = "値段：#{@item.price.to_s(:delimited)} ギル"
          .item-box__details
            .details-border
              %i.fas.fa-book-reader
              詳細
            = @item.details
          - if current_user == nil
          - elsif @item.seller_id == nil and current_user.id != @item.user_id
            = form_for @item do |f|
              = f.hidden_field :seller_id, value: current_user.id
              = f.submit '売ります', class: "btn-flat-border", data: { confirm: ' 本当に売りますか?' }
          - else
        .back-edit-destroy-box.margin-top-10
          .back-edit-destroy-box__back
            = link_to '戻る', :back
          .back-edit-destroy-box__edit-destroy
            - if current_user == nil
            - elsif current_user.id == @item.user_id and @item.seller_id == nil
              = link_to '編集', edit_item_path(@item)
              = link_to '削除', @item, class: "margin-left-10", method: :delete, data: { confirm: '本当に削除しますか?' }
            - else
        
    .main__side-menu
      = render 'side-menu'

app/views/items/show_close_myself.html.haml
#wrapper
  .main
    .main__list.shadow
      .main__list__page-title
        「買います」募集をした商品 - 売買成立
      - @items.each do |item|
        = link_to(item) do
          .item-box.link-hover
            - if item.seller_id != nil
              .triangle
              .item-box__day
                = item.created_at.to_s(:datetime_jp)
                = render partial: 'items/item', locals:{ item: item }
              .item-box__title
                = "「#{item.title}」"
              .item-box__price
                = "値段：#{item.price.to_s(:delimited)} ギル"
            - else
              .item-box__day
                = item.created_at.to_s(:datetime_jp)
                = render partial: 'items/item', locals:{ item: item }
              .item-box__title
                = "「#{item.title.to_s(:delimited)}」を買います！！"
              .item-box__price
                = "値段：#{item.price.to_s(:delimited)} ギル"
            .item-box__name
              .user-box
                .user-box__face
                  %i.fas.fa-user
                .user-box__name
                  = item.user.name
                  %br
                  .form-size-server-dc
                    = "#{item.user.dc}(#{item.user.server})"
              - if current_user == nil
              - elsif current_user.id == item.user_id && item.seller_id == nil
                .edit-destroy-box
                  = link_to '編集', edit_item_path(item)
                  = link_to '削除', item, class: "margin-left-10", method: :delete, data: { confirm: '本当に削除しますか?' }
              - else
              
      .main__list__pagination-box
        = paginate @items
                    
    .main__side-menu
      = render 'side-menu'

app/views/items/show_myself.html.haml
#wrapper
  .main
    .main__list.shadow
      .main__list__page-title
        「買います」募集をした商品 - 募集中
      - @items.each do |item|
        = link_to(item) do
          .item-container.link-hover
            - if item.seller_id != nil
              .triangle
              .item-container__day
                = item.created_at.to_s(:datetime_jp)
              .item-container__title
                = "「#{item.title}」"
              .item-container__price
                = "値段：#{item.price.to_s(:delimited)} ギル"
            - else
              .item-container__day
                = item.created_at.to_s(:datetime_jp)
              .item-container__title
                = "「#{item.title}」を買います！！"
              .item-container__price
                = "値段：#{item.price.to_s(:delimited)} ギル"
            .item-container__name
              .user-box
                .user-box__face
                  %i.fas.fa-user
                .user-box__name
                  = item.user.name
                  %br
                  .form-size-server-dc
                    = "#{item.user.dc}(#{item.user.server})"
            - if current_user == nil
            - elsif current_user.id == item.user_id and item.seller_id == nil
              .item-container__edit-destroy-box
                = link_to '編集', edit_item_path(item)
                = link_to '削除', item, class: "margin-left-10", method: :delete, data: { confirm: '本当に削除しますか?' }
            .item-container__watch
              = render partial: 'items/item', locals:{ item: item }

      .main__list__pagination-box
        = paginate @items

    .main__side-menu
      = render 'side-menu'

app/views/items/show_sell.html.haml
#wrapper
  .main
    .main__list.shadow
      .main__list__page-title
        「売ります」をした一覧
      - @items.each do |item|
        = link_to(item) do
          .item-container.link-hover
            - if item.seller_id != nil
              .triangle
              .item-container__day
                = item.created_at.to_s(:datetime_jp)
              .item-container__title
                = "「#{item.title}」"
              .item-container__price
                = "値段：#{item.price.to_s(:delimited)} ギル"
            - else
              .item-container__day
                = item.created_at.to_s(:datetime_jp)
              .item-container__title
                = "「#{item.title}」を買います！！"
              .item-container__price
                = "値段：#{item.price.to_s(:delimited)} ギル"
            .item-container__name
              .user-box
                .user-box__face
                  %i.fas.fa-user
                .user-box__name
                  = item.user.name
                  %br
                  .form-size-server-dc
                    = "#{item.user.dc}(#{item.user.server})"
            - if current_user == nil
            - elsif current_user.id == item.user_id and item.seller_id == nil
              .item-container__edit-destroy-box
                = link_to '編集', edit_item_path(item)
                = link_to '削除', item, class: "margin-left-10", method: :delete, data: { confirm: '本当に削除しますか?' }
            .item-container__watch
              = render partial: 'items/item', locals:{ item: item }
      
      .main__list__pagination-box
        = paginate @items
        
    .main__side-menu
      = render 'side-menu'

app/views/items/show_watch_list.haml
#wrapper
  .main
    .main__list.shadow
      .main__list__page-title
        ウォッチリストをした商品
      - @items.each do |item|
        = link_to(item) do
          .item-container.link-hover
            - if item.seller_id != nil
              .triangle
              .item-container__day
                = item.created_at.to_s(:datetime_jp)
              .item-container__title
                = "「#{item.title}」"
              .item-container__price
                = "値段：#{item.price.to_s(:delimited)} ギル"
            - else
              .item-container__day
                = item.created_at.to_s(:datetime_jp)
              .item-container__title
                = "「#{item.title}」"
              .item-container__price
                = "「#{item.title}」を買います！！"
            .item-container__name
              .user-box
                .user-box__face
                  %i.fas.fa-user
                .user-box__name
                  = item.user.name
                  %br
                  .form-size-server-dc
                    = "#{item.user.dc}(#{item.user.server})"
            - if current_user == nil
            - elsif current_user.id == item.user_id and item.seller_id == nil
              .item-container__edit-destroy-box
                = link_to '編集', edit_item_path(item)
                = link_to '削除', item, class: "margin-left-10", method: :delete, data: { confirm: '本当に削除しますか?' }
            .item-container__watch
              = render partial: 'items/item', locals:{ item: item }
      
      .main__list__pagination-box
        = paginate @items
                    
    .main__side-menu
      = render 'side-menu'