config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    # :registrations => 'signups',
    :sessions => 'users/sessions'   
  } 
  devise_scope :user do
    # get "user/:id", :to => "users/registrations#detail"
    get "user/:id", :to => "items#index"
    # get "signup", :to => "users/registrations#new"
    get "signup", :to => "users/registrations#new"
    post "signup", :to => "users/registrations#create"
    # get "signup", :to => "signups#new"
    # post "signup", :to => "signups#create"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "sign_in" => "devise/sessions#new"
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  # get "signup", :to => "signups#new"
  # post "signup", :to => "signups#create"

  resources :items do
    collection do
      get :show_myself
      get :show_close_myself
      get :show_sell
      get :show_watch_list
    end
  end

  post   '/like/:item_id' => 'likes#like',   as: 'like'
  delete '/like/:item_id' => 'likes#unlike', as: 'unlike'

end

app/views/layouts/_error_messages.html.haml
-if model.errors.any? 
  .alert
    %ul
      -model.errors.full_messages.each do |message| 
        %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 逆出品サイト
    -# %title Reverse Market
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    #wrapper
      .header
        .header__brand
          .header-box
            .header-box__brand
              = link_to "[逆出品サイト]", root_path, class: "size18 float-left"
              -# = link_to "[FF XIV Fan site]", root_path, class: "size18 float-left"
              -# = link_to "- 逆マーケットボード・テスト運用中 -", root_path, class: "size16 float-left"
            .header-box__search

              #notice= notice

        .header__l-header
          .header-container
            .head-my-character
              - if user_signed_in?
                .head-my-character__name
                  = current_user.name
                .head-my-character__status
                  = link_to "ログアウト", logout_path, data: { confirm: '本当にログアウトしますか?' }, class: "display-inline"
              - else
                .head-my-character__name
                  = link_to "ログイン", login_path, class: "display-inline"
                .head-my-character__status
                  = link_to "新規登録", signup_path, class: "display-inline"
        .header__main-nav

          = search_form_for @search, url: items_path do |f|
            = f.text_field :title_or_details_cont, class: "field_width300px", placeholder: 'キーワード検索'
            = f.submit ("検索する"), class: "display_none"

    = yield